#!/usr/bin/env bash
# Process and PID file

pidfile="/var/run/myscript.pid"

if [ ! -e "$pidfile" ]; then
  touch "$pidfile"
fi

sleep 2 &

echo "$!" > "$pidfile"

# This will print I hate the kill command, deletes the file and exits  when receiving a SIGTERM or SIGQUIT signal
trap 'echo "I hate the kill command"; rm "$pidfile"; exit' SIGTERM SIGQUIT

# prints Y U no love me?! when receiving a SIGINT signal
trap "echo Y U no love me?!" SIGINT

while true; do
  echo "To infinity and beyond"
  sleep 2
done
