#!/usr/bin/env bash
# Displays Best School 10 times and 'Hi' after the 9th using while and if

x=1

while [ $x -le 10 ]
do
    echo "Best School"
    if [ $x -eq 9 ]
    then
        echo "Hi"
    fi
    ((x++))
done
