#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
# Only displays the part of the name after the first dash.

l=$(ls)

for x in $l; do
  echo "$x" | cut -d '-' -f2
done
